# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: news
  description: News Section with heading, a image, a description and a link
  icon: wysiwyg
  tags:
    - Content

# Defines the structure of this component, as well as the default values
blueprint:
  title: ""
  description_html: ""
  link_url: ""
  show_posts: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: News
  description_html: Hey, I'm a description
  link_url: /news

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
