title: Hamza

plugins:
  - jekyll-bookshop
  - jekyll-sitemap
  - jekyll/tagging

# Multiple bookshops can be used on one website,
# or different production / staging locations.
bookshop_locations:
  - ../component-library

exclude:
  - postcss.config.js
  - node_modules

include:
  - _cloudcannon

collections_dir: 'collections'

collections:
  pages:
    output: true
    permalink: /:title/
  projects:
    output: true
    permalink: /project/:slug
  affiliations:
    output: false
  posts:
    output: true
    permalink: /news/:slug
  publications:
    output: true
    permalink: /publications/:slug
  research_projects:
    output: true
    permalink: /projects/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: pages
      path: _pages/index.html
    values:
      permalink: /
  - scope:
      type: projects
    values:
      layout: project
  - scope:
      type: posts
    values:
      layout: post
  - scope:
      type: publications
    values:
      layout: publication
  - scope:
      type: projects
    values:
      layout:project

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: /:title
