title: Hamza Abdelhedi – Neuro-AI Researcher & Open Science Advocate
description: PhD Student in Biomedical Engineering at UdeM & MILA. Researching the intersection of Artificial and Biological Neural Networks. Open science and community-focused.
social_media_share_image: /images/main/my-image.jpg
disqus-identifier: # Add your Disqus shortname here to enable comments
google-analytics: # Add your GA4 Measurement ID here (e.g., G-XXXXXXXXXX)