# Metadata about this component, to be used in the CMS
spec:
  structures: []
  label: Affiliation Card
  description: Affiliation card used for Affiliation lists
  icon: wysiwyg
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  Affiliation-item:
    name: ""
    position: ""
    blurb: ""
    image: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  Affiliation-item:
    name: Hello World
    position: Author
    blurb: Lorem Ipsum
    image: https://placekitten.com/1000/600

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
